---
apiVersion: v1                                                                                                       
kind: Secret                                                                                                         
metadata:                                                                                                            
  name: {{ .Values.registry_secret.name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
type: kubernetes.io/dockerconfigjson
data:                                                                                                                
  .dockerconfigjson: {{ .Values.registry_secret.data | b64enc }}
