{{- with .Values.kettleWeigher -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    {{- include "kettle-weigher.labels" $ | nindent 4 }}
    app.kubernetes.io/instance: {{ .name }}
spec:
  type: ClusterIP
  ports: 
    {{- include "kettle-weigher.servicePort" $ | fromYaml | list | toYaml | nindent 4 }}
  selector:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ .name }}
{{- end -}}
